[package]
name = "tcplscan"
version = "0.1.1"
edition = "2021"
description = "A tool to keep track of class complexity of a PHP project"
repository = "https://github.com/OchirErkhembayar/tcplscan"
license = "MIT OR Apache-2.0"

[dependencies]
colored = "2.0.4"
git2 = "0.17.2"
lazy_static = "1.4.0"
